export const randomData = {
  sheetName: 'Student Report',
  columns: ['Name', 'Age', 'Gender', 'Email', 'Phone', 'Address'],
  rows: [
    {
      Name: 'John Doe',
      Age: 20,
      Gender: 'Male',
      Email: 'john.doe@example.com',
      Phone: '1234567890',
      Address: '123 Main St, Anytown, USA',
    },
    {
      Name: 'Jane Smith',
      Age: 21,
      Gender: 'Female',
      Email: 'jane.smith@example.com',
      Phone: '0987654321',
      Address: '456 Elm St, Anytown, USA',
    },
    {
      Name: 'Jim Beam',
      Age: 22,
      Gender: 'Male',
      Email: 'jim.beam@example.com',
      Phone: '1112223333',
      Address: '789 Oak St, Anytown, USA',
    },
    {
      Name: 'Jill Johnson',
      Age: 23,
      Gender: 'Female',
      Email: 'jill.johnson@example.com',
      Phone: '4445556666',
      Address: '321 Pine St, Anytown, USA',
    },
    {
      Name: 'Jack White',
      Age: 24,
      Gender: 'Male',
      Email: 'jack.white@example.com',
      Phone: '7778889999',
      Address: '654 Maple St, Anytown, USA',
    },
    {
      Name: 'Jill Johnson',
      Age: 23,
      Gender: 'Female',
      Email: 'jill.johnson@example.com',
      Phone: '4445556666',
      Address: '321 Pine St, Anytown, USA',
    },
    {
      Name: 'Mike Johnson',
      Age: 23,
      Gender: 'Female',
      Email: 'mike.johnson@example.com',
      Phone: '4445556666',
      Address: '321 Pine St, Anytown, USA',
    },
    {
      Name: 'John Johnson',
      Age: 23,
      Gender: 'Female',
      Email: 'john.johnson@example.com',
      Phone: '4445556666',
      Address: '321 Pine St, Anytown, USA',
    },
    {
      Name: 'Jane Johnson',
      Age: 23,
      Gender: 'Female',
      Email: 'jane.johnson@example.com',
      Phone: '4445556666',
      Address: '321 Pine St, Anytown, USA',
    },
    {
      Name: 'Jim Johnson',
      Age: 23,
      Gender: 'Female',
      Email: 'jim.johnson@example.com',
      Phone: '4445556666',
      Address: '321 Pine St, Anytown, USA',
    },
  ],
};
